### ISSUE TITLE
Запуск демо локально

### ISSUE THREAD

**Issue by mavsan** [SleepingOwlAdmin/demo#25]
Делаю по инструкции все, composer в конце выдал (php artisan key:generate и php artisan migrate --seed эта же ошибка):
![image](https://cloud.githubusercontent.com/assets/5114650/24131002/c4426cea-0e37-11e7-9cd5-2b384918a949.png)

Заходим на сайт:

![image](https://cloud.githubusercontent.com/assets/5114650/24130981/9887c8ca-0e37-11e7-8e01-577a3d364f17.png)

Лечится комментированием в настройках секций провайдера `AdminSectionsServiceProvider`:
~~~
        'App\Model\News5'           => 'Admin\Http\Sections\News5',

//        'App\Model\Contact5'        => 'Admin\Http\Sections\Contacts5',
//        'App\Model\Contact6'        => 'Admin\Http\Sections\Contacts6',
//        'App\Model\NewsTabsBadges'  => 'Admin\Http\Sections\TabsBadges',

        'App\Role'                  => 'Admin\Http\Sections\Roles',
~~~

**Comment by mavsan** [comment]
К стати, Policies тоже не  работают в локальной версии.

**Comment by lunatig** [comment]
composer update решит проблему.

**Comment by mavsan** [comment]
Автотесты так и не пройдены (не удивительно - не устанавливается).
Все удалил, скачал свежее, заново устанавливаю. Вот результат работы (на всякий случай - весь лог выкладываю) composer install:
~~~
H:\OpenServer\domains\sleepingOwl.demo>composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 81 installs, 0 updates, 0 removals
  - Installing symfony/class-loader (v3.2.2): Loading from cache
  - Installing vlucas/phpdotenv (v2.4.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.3.0): Loading from cache
  - Installing symfony/var-dumper (v3.1.10): Loading from cache
  - Installing symfony/translation (v3.1.10): Loading from cache
  - Installing symfony/routing (v3.1.10): Loading from cache
  - Installing symfony/process (v3.1.10): Loading from cache
  - Installing symfony/http-foundation (v3.1.10): Loading from cache
  - Installing symfony/event-dispatcher (v3.2.2): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/debug (v3.1.10): Loading from cache
  - Installing symfony/http-kernel (v3.1.10): Loading from cache
  - Installing symfony/finder (v3.1.10): Loading from cache
  - Installing symfony/console (v3.1.10): Loading from cache
  - Installing swiftmailer/swiftmailer (v5.4.5): Loading from cache
  - Installing paragonie/random_compat (v2.0.4): Loading from cache
  - Installing ramsey/uuid (3.5.2): Loading from cache
  - Installing nikic/php-parser (v3.0.2): Loading from cache
  - Installing jakub-onderka/php-console-color (0.1): Loading from cache
  - Installing jakub-onderka/php-console-highlighter (v0.3.2): Loading from cache
  - Installing dnoegel/php-xdg-base-dir (0.1): Loading from cache
  - Installing psy/psysh (v0.8.1): Loading from cache
  - Installing nesbot/carbon (1.22.1): Loading from cache
  - Installing mtdowling/cron-expression (v1.2.0): Loading from cache
  - Installing monolog/monolog (1.22.0): Loading from cache
  - Installing league/flysystem (1.0.34): Loading from cache
  - Installing symfony/polyfill-util (v1.3.0): Loading from cache
  - Installing symfony/polyfill-php56 (v1.3.0): Loading from cache
  - Installing jeremeamia/superclosure (2.3.0): Loading from cache
  - Installing doctrine/inflector (v1.1.0): Loading from cache
  - Installing classpreloader/classpreloader (3.1.0): Loading from cache
  - Installing laravel/framework (v5.3.30): Loading from cache
  - Installing barryvdh/reflection-docblock (v2.0.4): Loading from cache
  - Installing barryvdh/laravel-ide-helper (v2.2.3): Loading from cache
  - Installing baum/baum (1.1.1): Loading from cache
  - Installing doctrine/lexer (v1.0.1): Loading from cache
  - Installing doctrine/collections (v1.4.0): Loading from cache
  - Installing doctrine/cache (v1.6.1): Loading from cache
  - Installing doctrine/annotations (v1.3.1): Loading from cache
  - Installing doctrine/common (v2.7.2): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.3.1): Loading from cache
  - Installing intervention/image (2.3.10): Loading from cache
  - Installing laravelcollective/html (v5.3.1): Loading from cache
  - Installing kodicomponents/support (v0.3.6): Loading from cache
  - Installing kodicomponents/navigation (v0.6.5): Loading from cache
  - Installing kodicms/laravel-assets (v0.3.5): Loading from cache
  - Installing erusev/parsedown (1.6.1): Loading from cache
  - Installing doctrine/dbal (v2.5.10): Loading from cache
  - Installing davejamesmiller/laravel-breadcrumbs (3.0.2): Loading from cache
  - Installing laravelrus/sleepingowl (dev-development 2f8d770): Loading from cache
  - Installing fzaninotto/faker (v1.6.0): Loading from cache
  - Installing hamcrest/hamcrest-php (v1.2.2): Loading from cache
  - Installing mockery/mockery (0.9.7): Loading from cache
  - Installing webmozart/assert (1.2.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0): Loading from cache
  - Installing phpdocumentor/type-resolver (0.2.1): Loading from cache
  - Installing phpdocumentor/reflection-docblock (3.1.1): Loading from cache
  - Installing phpunit/php-token-stream (1.4.9): Loading from cache
  - Installing symfony/yaml (v3.2.2): Loading from cache
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing sebastian/recursion-context (2.0.0): Loading from cache
  - Installing sebastian/object-enumerator (2.0.0): Loading from cache
  - Installing sebastian/global-state (1.1.1): Loading from cache
  - Installing sebastian/exporter (2.0.0): Loading from cache
  - Installing sebastian/environment (2.0.0): Loading from cache
  - Installing sebastian/diff (1.4.1): Loading from cache
  - Installing sebastian/comparator (1.2.4): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing doctrine/instantiator (1.0.5): Loading from cache
  - Installing phpunit/phpunit-mock-objects (3.4.3): Loading from cache
  - Installing phpunit/php-timer (1.0.8): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.2): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.0): Loading from cache
  - Installing phpunit/php-code-coverage (4.0.5): Loading from cache
  - Installing phpspec/prophecy (v1.6.2): Loading from cache
  - Installing myclabs/deep-copy (1.6.0): Loading from cache
  - Installing phpunit/phpunit (5.7.9): Loading from cache
  - Installing symfony/css-selector (v3.1.10): Loading from cache
  - Installing symfony/dom-crawler (v3.1.10): Loading from cache
symfony/class-loader suggests installing symfony/polyfill-apcu (For using ApcClassLoader on HHVM)
symfony/var-dumper suggests installing ext-symfony_debug ()
symfony/translation suggests installing symfony/config ()
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/dependency-injection (For loading routes from a service)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/http-kernel suggests installing symfony/browser-kit ()
symfony/http-kernel suggests installing symfony/config ()
symfony/http-kernel suggests installing symfony/dependency-injection ()
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
ramsey/uuid suggests installing ext-libsodium (Provides the PECL libsodium extension for use with the SodiumRandomGenerator)
ramsey/uuid suggests installing ext-uuid (Provides the PECL UUID extension for use with the PeclUuidTimeGenerator and PeclUuidRandomGenerator)
ramsey/uuid suggests installing ircmaxell/random-lib (Provides RandomLib for use with the RandomLibAdapter)
ramsey/uuid suggests installing moontoast/math (Provides support for converting UUID to 128-bit integer (in string form).)
ramsey/uuid suggests installing ramsey/uuid-console (A console application for generating UUIDs with ramsey/uuid)
ramsey/uuid suggests installing ramsey/uuid-doctrine (Allows the use of Ramsey\Uuid\Uuid as Doctrine field type.)
psy/psysh suggests installing ext-pcntl (Enabling the PCNTL extension makes PsySH a lot happier :))
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing ext-posix (If you have PCNTL, you'll want the POSIX extension as well.)
psy/psysh suggests installing ext-readline (Enables support for arrow-key history navigation, and showing and manipulating command history.)
psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install doesn't already support readline or libedit.)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem suggests installing league/flysystem-copy (Allows you to use Copy.com storage)
league/flysystem suggests installing league/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
laravel/framework suggests installing aws/aws-sdk-php (Required to use the SQS queue driver and SES mail driver (~3.0).)
laravel/framework suggests installing guzzlehttp/guzzle (Required to use the Mailgun and Mandrill mail drivers and the ping methods on schedules (~5.3|~6.0).)
laravel/framework suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (~1.0).)
laravel/framework suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (~1.0).)
laravel/framework suggests installing pda/pheanstalk (Required to use the beanstalk queue driver (~3.0).)
laravel/framework suggests installing predis/predis (Required to use the redis cache and queue drivers (~1.0).)
laravel/framework suggests installing pusher/pusher-php-server (Required to use the Pusher broadcast driver (~2.0).)
laravel/framework suggests installing symfony/psr-http-message-bridge (Required to use psr7 bridging features (0.2.*).)
barryvdh/reflection-docblock suggests installing dflydev/markdown (~1.0)
intervention/image suggests installing ext-imagick (to use Imagick based image processing.)
intervention/image suggests installing intervention/imagecache (Caching extension for the Intervention Image library)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize


  [BadMethodCallException]
  makePage


Script php artisan optimize handling the post-install-cmd event returned with error code 1

H:\OpenServer\domains\sleepingOwl.demo>
~~~

По совету товарищей сделал composer update:

~~~
composer update
    1/10:       http://packagist.org/p/provider-archived$e030a79ae57353618444b1fb2ab7e99aa0415496b2957b120610ad9a0a76a132.json
    2/10:       http://packagist.org/p/provider-latest$ca4c3b6ca24fbbcc3a1ee70927ecc0adea497eebe1a3174bdae954ce6d41a080.json
    3/10:       http://packagist.org/p/provider-2013$b34ef80d089492535e12ed463b74b44743e9ad600c55c541394d2cbbd1eae5bb.json
    4/10:       http://packagist.org/p/provider-2016$9392da302b1e0a2ab81cf189e3700aa9e538acb3724984e22986a99b0ec88dc3.json
    5/10:       http://packagist.org/p/provider-2016-04$81d9d242d727dc709f05caeadb86fbab412609dfcc5920bd14f2de9d6376cbb7.json
    6/10:       http://packagist.org/p/provider-2016-07$5168d810b847aa741de04cb3aafbf98fee1aa89494a5393aaf876e2f7b7d6c30.json
    7/10:       http://packagist.org/p/provider-2014$d55f61945f2e33d17350891323c1fed76a692d0a93046293afb47b6bb276358e.json
    8/10:       http://packagist.org/p/provider-2015$cc094ee6602966544aa4cfc9e2540fc5ca46355cd0450fdd710c0d3dc0190528.json
    9/10:       http://packagist.org/p/provider-2017-01$b6292ac475e1a6f060eeff7c173743069dbf6b16f32233217b039e930a0d4af0.json
    10/10:      http://packagist.org/p/provider-2016-10$8adab2b50121686966525ff96f5aa3a420b5e565076be77b2eeee5c449dbfdcd.json
    Finished: success: 10, skipped: 0, failure: 0, total: 10
Loading composer repositories with package information
Updating dependencies (including require-dev)
    1/7:        https://codeload.github.com/thephpleague/flysystem/legacy.zip/d9c1698582dfbfbd092ec9c5c3325f862cdb3297
    2/7:        https://codeload.github.com/ramsey/uuid/legacy.zip/0b7bdfb180e72c8d76e75a649ced67e392201458
    3/7:        https://codeload.github.com/guzzle/psr7/legacy.zip/f5b8a8512e2b58b0071a7280e39f14f72e05d87c
    4/7:        https://codeload.github.com/Intervention/image/legacy.zip/e8881fd99b9804b29e02d6d1c2c15ee459335cf1
    5/7:        https://codeload.github.com/bobthecow/psysh/legacy.zip/1dd4bbbc64d71e7ec075ffe82b42d9e096dc8d5e
    6/7:        https://codeload.github.com/sebastianbergmann/phpunit/legacy.zip/68752b665d3875f9a38a357e3ecb35c79f8673bf
    7/7:        https://codeload.github.com/LaravelRUS/SleepingOwlAdmin/legacy.zip/ed9925ca94da306670a8e529959caa5261f4905c
    Finished: success: 7, skipped: 0, failure: 0, total: 7
Package operations: 0 installs, 25 updates, 0 removals
  - Updating guzzlehttp/psr7 (1.3.1 => 1.4.2): Loading from cache
  - Updating intervention/image (2.3.10 => 2.3.11): Loading from cache
  - Updating symfony/class-loader (v3.2.2 => v3.2.6): Loading from cache
  - Updating symfony/event-dispatcher (v3.2.2 => v3.2.6): Loading from cache
  - Updating swiftmailer/swiftmailer (v5.4.5 => v5.4.6): Loading from cache
  - Updating paragonie/random_compat (v2.0.4 => v2.0.10): Loading from cache
  - Updating ramsey/uuid (3.5.2 => 3.6.0): Loading from cache
  - Updating nikic/php-parser (v3.0.2 => v3.0.5): Loading from cache
  - Updating psy/psysh (v0.8.1 => v0.8.3): Loading from cache
  - Updating monolog/monolog (1.22.0 => 1.22.1): Loading from cache
  - Updating league/flysystem (1.0.34 => 1.0.36): Loading from cache
  - Updating barryvdh/laravel-ide-helper (v2.2.3 => v2.3.2): Loading from cache
  - Updating mockery/mockery (0.9.7 => 0.9.9): Loading from cache
  - Updating symfony/yaml (v3.2.2 => v3.2.6): Loading from cache
  - Updating sebastian/object-enumerator (2.0.0 => 2.0.1): Loading from cache
  - Updating phpunit/php-timer (1.0.8 => 1.0.9): Loading from cache
  - Updating sebastian/code-unit-reverse-lookup (1.0.0 => 1.0.1): Loading from cache
  - Updating phpunit/php-token-stream (1.4.9 => 1.4.11): Loading from cache
  - Updating phpunit/php-code-coverage (4.0.5 => 4.0.7): Loading from cache
  - Updating phpspec/prophecy (v1.6.2 => v1.7.0): Loading from cache
  - Updating phpunit/phpunit (5.7.9 => 5.7.17): Loading from cache
  - Updating doctrine/annotations (v1.3.1 => v1.4.0): Loading from cache
  - Updating doctrine/dbal (v2.5.10 => v2.5.12): Loading from cache
  - Updating kodicomponents/navigation (v0.6.5 => v0.6.6): Loading from cache
  - Removing laravelrus/sleepingowl (dev-development 2f8d770)
  - Installing laravelrus/sleepingowl (dev-development ed9925c): Loading from cache
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
Compiling common classes
> php artisan sleepingowl:update


  [Symfony\Component\Console\Exception\InvalidArgumentException]
  The "force" option does not exist.


Script php artisan sleepingowl:update handling the post-update-cmd event returned with error code 1
~~~

Детали ошибки (storage/logs/laravel.log):

~~~
[2017-03-22 00:41:59] production.ERROR: exception 'BadMethodCallException' with message 'makePage' in H:\OpenServer\domains\sleepingOwl.demo\vendor\laravelrus\sleepingowl\src\Model\ModelConfigurationManager.php:553
Stack trace:
#0 H:\OpenServer\domains\sleepingOwl.demo\admin\Http\Sections\Contacts5.php(54): SleepingOwl\Admin\Model\ModelConfigurationManager->__call('makePage', Array)
#1 H:\OpenServer\domains\sleepingOwl.demo\admin\Http\Sections\Contacts5.php(54): Admin\Http\Sections\Contacts5->makePage(300)
#2 H:\OpenServer\domains\sleepingOwl.demo\vendor\laravelrus\sleepingowl\src\Admin.php(95): Admin\Http\Sections\Contacts5->initialize()
#3 H:\OpenServer\domains\sleepingOwl.demo\vendor\laravelrus\sleepingowl\src\Providers\AdminSectionsServiceProvider.php(31): SleepingOwl\Admin\Admin->register(Object(Admin\Http\Sections\Contacts5))
#4 H:\OpenServer\domains\sleepingOwl.demo\admin\Providers\AdminSectionsServiceProvider.php(63): SleepingOwl\Admin\Providers\AdminSectionsServiceProvider->boot(Object(SleepingOwl\Admin\Admin))
#5 [internal function]: Admin\Providers\AdminSectionsServiceProvider->boot(Object(SleepingOwl\Admin\Admin))
#6 H:\OpenServer\domains\sleepingOwl.demo\vendor\laravel\framework\src\Illuminate\Container\Container.php(508): call_user_func_array(Array, Array)
#7 H:\OpenServer\domains\sleepingOwl.demo\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(769): Illuminate\Container\Container->call(Array)
#8 H:\OpenServer\domains\sleepingOwl.demo\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(752): Illuminate\Foundation\Application->bootProvider(Object(Admin\Providers\AdminSectionsServiceProvider))
#9 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Admin\Providers\AdminSectionsServiceProvider), 15)
#10 H:\OpenServer\domains\sleepingOwl.demo\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(753): array_walk(Array, Object(Closure))
#11 H:\OpenServer\domains\sleepingOwl.demo\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(17): Illuminate\Foundation\Application->boot()
#12 H:\OpenServer\domains\sleepingOwl.demo\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#13 H:\OpenServer\domains\sleepingOwl.demo\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(267): Illuminate\Foundation\Application->bootstrapWith(Array)
#14 H:\OpenServer\domains\sleepingOwl.demo\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(113): Illuminate\Foundation\Console\Kernel->bootstrap()
#15 H:\OpenServer\domains\sleepingOwl.demo\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 {main}  
[2017-03-22 00:51:06] production.ERROR: exception 'Symfony\Component\Console\Exception\InvalidArgumentException' with message 'The "force" option does not exist.' in H:\OpenServer\domains\sleepingOwl.demo\vendor\symfony\console\Input\Input.php:157
Stack trace:
#0 H:\OpenServer\domains\sleepingOwl.demo\vendor\laravel\framework\src\Illuminate\Console\Command.php(263): Symfony\Component\Console\Input\Input->getOption('force')
#1 H:\OpenServer\domains\sleepingOwl.demo\vendor\laravel\framework\src\Illuminate\Console\ConfirmableTrait.php(25): Illuminate\Console\Command->option('force')
#2 H:\OpenServer\domains\sleepingOwl.demo\vendor\laravelrus\sleepingowl\src\Console\Installation\Command.php(35): SleepingOwl\Admin\Console\Installation\Command->confirmToProceed('SleepingOwl Adm...')
#3 [internal function]: SleepingOwl\Admin\Console\Installation\Command->fire(Object(Illuminate\Filesystem\Filesystem))
#4 H:\OpenServer\domains\sleepingOwl.demo\bootstrap\cache\compiled.php(1375): call_user_func_array(Array, Array)
#5 H:\OpenServer\domains\sleepingOwl.demo\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Illuminate\Container\Container->call(Array)
#6 H:\OpenServer\domains\sleepingOwl.demo\vendor\symfony\console\Command\Command.php(261): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 H:\OpenServer\domains\sleepingOwl.demo\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 H:\OpenServer\domains\sleepingOwl.demo\vendor\symfony\console\Application.php(817): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 H:\OpenServer\domains\sleepingOwl.demo\vendor\symfony\console\Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(SleepingOwl\Admin\Console\Commands\UpdateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 H:\OpenServer\domains\sleepingOwl.demo\vendor\symfony\console\Application.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 H:\OpenServer\domains\sleepingOwl.demo\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 H:\OpenServer\domains\sleepingOwl.demo\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 {main}  
~~~
